### ISSUE TITLE
Mark's timeline

### ISSUE THREAD

**Issue by eguil** [ES-DOC/esdoc-project#32]
- [x] Model spreadsheet ready for beta testing #39 
- [x] Static prototype further info URL landing page #43 
- [x] Transform spreadsheets to CIM for variety of docs #21 
- [x] CDF2CIM web-service dev & ops
- [x] ERRATA web-service dev & ops
- [x] Publish model CIM documents from spreadsheet
- [ ] UKMO publishing
- [ ] Render model CIM documents in viewer #19 
- [ ] Transform ensemble JSON to CIM #20

**Comment by eguil** [comment]
superseded by Mark's project at top level
